"""init schema

Revision ID: bd3766df6d37
Revises: 
Create Date: 2026-07-03 10:38:00.510188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd3766df6d37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.Enum('LIGHT', 'STANDARD', 'NETWORK', name='business_plan', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'PAUSED', 'CHURNED', name='business_status', native_enum=False, length=20), nullable=False),
    sa.Column('gis_2gis_url', sa.String(length=512), nullable=True),
    sa.Column('yandex_maps_url', sa.String(length=512), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('crm_type', sa.Enum('YCLIENTS', 'AMOCRM', 'BITRIX24', name='crm_type', native_enum=False, length=20), nullable=True),
    sa.Column('crm_webhook_secret', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('redirect_slug', sa.String(length=64), nullable=False),
    sa.Column('gis_2gis_url', sa.String(length=512), nullable=True),
    sa.Column('yandex_maps_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('redirect_slug')
    )
    op.create_table('opted_out_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', 'business_id', name='uq_opted_out_phone_business')
    )
    op.create_index(op.f('ix_opted_out_numbers_phone'), 'opted_out_numbers', ['phone'], unique=False)
    op.create_table('review_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('client_phone', sa.String(length=32), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('master_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'RATED', 'GENERATED', 'COMPLETED', 'OPTED_OUT', name='review_request_status', native_enum=False, length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('generated_review', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_requests_client_phone'), 'review_requests', ['client_phone'], unique=False)
    op.create_index(op.f('ix_review_requests_status'), 'review_requests', ['status'], unique=False)
    op.create_table('message_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_request_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='message_direction', native_enum=False, length=10), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_request_id'], ['review_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_log')
    op.drop_index(op.f('ix_review_requests_status'), table_name='review_requests')
    op.drop_index(op.f('ix_review_requests_client_phone'), table_name='review_requests')
    op.drop_table('review_requests')
    op.drop_index(op.f('ix_opted_out_numbers_phone'), table_name='opted_out_numbers')
    op.drop_table('opted_out_numbers')
    op.drop_table('locations')
    op.drop_table('businesses')
    # ### end Alembic commands ###
